### ISSUE TITLE
Readme.md : Chinese translate 😊

### ISSUE THREAD

**Issue by chinanf-boy** [transitive-bullshit/awesome-puppeteer#7]
### 2. this source repo Add a chinese repo link

> What would you like ? 😊

https://github.com/chinanf-boy/awesome-puppeteer-zh

**Comment by transitive-bullshit** [comment]
@chinanf-boy that'd be awesome! 👍 👍

**Comment by chinanf-boy** [comment]
Which would you like

**Comment by transitive-bullshit** [comment]
Please create a Pull Request that adds a `readme.zh.md` and a link to it in the English readme.

Thanks!

**Comment by chinanf-boy** [comment]
### Here we go

#8

**Comment by transitive-bullshit** [comment]
Thanks again!
